---
title: "class14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Examine Asthma SNPs in MXL (Mexican Ancestry Los Angeles)
```{r}
data <- read.csv("373531-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")
```

Find amount of each genotype
```{r}
gen_count <- table(data$Genotype..forward.strand.)
gen_count
```
Find Proportions
```{r}
genotypes <- round((gen_count/sum(gen_count))*100, 2)
genotypes
```

There are `r genotypes[1]` % AA genotypes in this population

##Interpreting base qualities in R
```{r}
#install.packages("seqinr")
#install.packages("gtools")
```

```{r}
library(seqinr)
library(gtools)
phred <- asc( s2c("DDDDCDEDCDDDDBBDDDCC@")) - 33
phred
```

```{r}
genes <- read.table("https://bioboot.github.io/bimm143_S18/class-material/rs8067378_ENSG00000172057.6.txt")

```

```{r}
summary(genes)
```

```{r}
inds.ag <- genes$geno == "A/G"
summary( genes$exp[inds.ag] )
```
```{r}
inds.ag <- genes$geno == "A/A"
summary( genes$exp[inds.ag] )
```
```{r}
inds.ag <- genes$geno == "G/G"
summary( genes$exp[inds.ag] )
```




```{r}
p <- boxplot(exp~geno, data=genes, xlab="rs8067378 genotype", ylab="ENSG00000172057.4 (RPKM)", notch=T)
```

```{r}
library(ggplot2)
ggplot(genes, aes(exp, fill = geno)) + geom_density(alpha = 0.2)
```

